<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5VGcZIJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5VGcZIJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5VGcZIJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5VGcZIJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5VGcZIJ\App_KernelDevDebugContainer([
    'container.build_hash' => '5VGcZIJ',
    'container.build_id' => '8f893b53',
    'container.build_time' => 1646059535,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5VGcZIJ');
