<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxTI6NE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxTI6NE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxTI6NE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxTI6NE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxTI6NE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxTI6NE',
    'container.build_id' => 'a9a3675e',
    'container.build_time' => 1644421757,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxTI6NE');
