<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8fB9pWw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8fB9pWw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8fB9pWw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8fB9pWw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8fB9pWw\App_KernelDevDebugContainer([
    'container.build_hash' => '8fB9pWw',
    'container.build_id' => '879c0810',
    'container.build_time' => 1643883539,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8fB9pWw');
