<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'serv' => [[], ['_controller' => 'App\\Controller\\ServDmsController::index'], [], [['text', '/serv']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\ServDmsController::accueil'], [], [['text', '/accueil']], [], [], []],
    'newUsers' => [[], ['_controller' => 'App\\Controller\\ServDmsController::newUsers'], [], [['text', '/newUsers']], [], [], []],
    'insertUser' => [[], ['_controller' => 'App\\Controller\\ServDmsController::insertUser'], [], [['text', '/insertUser']], [], [], []],
    'listeUsers' => [[], ['_controller' => 'App\\Controller\\ServDmsController::listeUsers'], [], [['text', '/listeUsers']], [], [], []],
    'supprimer_Utilisateur' => [['id'], ['_controller' => 'App\\Controller\\ServDmsController::supprimerUtilisateur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimerUtilisateur']], [], [], []],
    'deco_Utilisateur' => [[], ['_controller' => 'App\\Controller\\ServDmsController::decoUtilisateur'], [], [['text', '/decoUtilisateur']], [], [], []],
    'trait_Fichier' => [[], ['_controller' => 'App\\Controller\\ServDmsController::trait_Fichier'], [], [['text', '/trait_Fichier']], [], [], []],
    'ajoueFichier' => [[], ['_controller' => 'App\\Controller\\ServDmsController::ajouefichier'], [], [['text', '/ajoueFichier']], [], [], []],
    'listFichier' => [[], ['_controller' => 'App\\Controller\\ServDmsController::listfichier'], [], [['text', '/listFichier']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
